[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "template"
version = "1.1.0"
requires-python = ">=3.13"
dependencies = ["prairielearn", "chevron", "lxml"]

[dependency-groups]
dev = [
    "ipython",
    "pl-vendor>=0.4.2",
    "pyright",
    "pytest",
    "ruff",
]

[tool.uv.sources.prairielearn]
git = "https://github.com/PrairieLearn/PrairieLearn.git"
rev = "0952fbfcde4fee9d8a007e87deaeb49970598c05" # deliberately pinned with vendored pl-symbolic-input
subdirectory = "apps/prairielearn/python"

[tool.pyright]
include = ["elements", "questions", "scripts", "src"]
exclude = ["**/vendor", "**/node_modules", "**/__pycache__", "**/.*", ".venv"]

[tool.ruff]
exclude = ["**/vendor", "scripts/prompts/output"]

[tool.pl-vendor]
required-version = "^0.4"

[tool.pl-vendor.packages.prairielearn-symbolic-input]
path = "elements/pl-big-operator-input/vendor/prairielearn/pl-symbolic-input"
url = "https://github.com/PrairieLearn/PrairieLearn.git"
commit = "0952fbfcde4fee9d8a007e87deaeb49970598c05"
subdirectory = "apps/prairielearn/elements/pl-symbolic-input"
